CREATE TABLE [dbo].[Notes]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    [UserId] UNIQUEIDENTIFIER NOT NULL,
	[Text] NVARCHAR(MAX), 
    CONSTRAINT [FK_Notes_To_Users] FOREIGN KEY ([UserId]) REFERENCES [Users]([Id]), 
)
